import Foundation

struct GoogleCloudModels {
    
    static func createModels() -> [ConnectionModel] {
        return [
            ConnectionModel(
                connectionId: EnumConnectionCode.GOOGLE_CLOUD.connectionId,
                modelId: EnumConnectionModelCode.GOOGLE_GEMINI_FLASH_IMAGE.modelId,
                modelCode: EnumConnectionModelCode.GOOGLE_GEMINI_FLASH_IMAGE,
                modelSetType: EnumSetType.GENERATE,
                modelName: "Nano Banana (2.5 Flash)",
                modelDescription: "Gemini 2.5 Flash Image - Fast and efficient native image generation at 1024px resolution.",
                modelSupportedParams: ConnectionModelSupportParams(
                    prompt: true,
                    negativePrompt: false,
                    maxPromptLength: 4000,
                    dimensions: ["1024x1024", "832x1248", "1248x832", "864x1184", "1184x864", "896x1152", "1152x896", "768x1344", "1344x768", "1536x672"],
                    quality: false,
                    variant: false,
                    style: false,
                    count: 6,
                    autoEnhance: false,
                    responseModalities: []
                ),
                modelLaunchDate: getDateFromString("2024-11-01"),
                modelGenerateBaseURL: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-image:generateContent",
                modelAPIDocumentationURL: "https://ai.google.dev/gemini-api/docs/image-generation",
                active: true
            ),
            ConnectionModel(
                connectionId: EnumConnectionCode.GOOGLE_CLOUD.connectionId,
                modelId: EnumConnectionModelCode.GOOGLE_GEMINI_FLASH_IMAGE_EDIT.modelId,
                modelCode: EnumConnectionModelCode.GOOGLE_GEMINI_FLASH_IMAGE_EDIT,
                modelSetType: EnumSetType.EDIT_PROMPT,
                modelName: "Nano Banana (2.5 Flash)",
                modelDescription: "Gemini 2.5 Flash Image - Edit images with text prompts for mask-free modifications.",
                modelSupportedParams: ConnectionModelSupportParams(
                    prompt: true,
                    negativePrompt: false,
                    maxPromptLength: 4000,
                    dimensions: ["1024x1024", "832x1248", "1248x832", "864x1184", "1184x864", "896x1152", "1152x896", "768x1344", "1344x768", "1536x672"],
                    quality: false,
                    variant: false,
                    style: false,
                    count: 6,
                    autoEnhance: false,
                    responseModalities: []
                ),
                modelLaunchDate: getDateFromString("2024-11-01"),
                modelGenerateBaseURL: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-image:generateContent",
                modelAPIDocumentationURL: "https://ai.google.dev/gemini-api/docs/image-generation",
                active: true
            ),
            ConnectionModel(
                connectionId: EnumConnectionCode.GOOGLE_CLOUD.connectionId,
                modelId: EnumConnectionModelCode.GOOGLE_GEMINI_PRO_IMAGE.modelId,
                modelCode: EnumConnectionModelCode.GOOGLE_GEMINI_PRO_IMAGE,
                modelSetType: EnumSetType.GENERATE,
                modelName: "Nano Banana Pro (3 Pro)",
                modelDescription: "Gemini 3 Pro Image Preview - Professional image generation. SD=2K, HD=4K resolution.",
                modelSupportedParams: ConnectionModelSupportParams(
                    prompt: true,
                    negativePrompt: false,
                    maxPromptLength: 4000,
                    dimensions: ["1024x1024", "832x1248", "1248x832", "864x1184", "1184x864", "896x1152", "1152x896", "768x1344", "1344x768", "1536x672"],
                    quality: true,
                    variant: false,
                    style: false,
                    count: 6,
                    autoEnhance: false,
                    responseModalities: [.TEXT, .IMAGE]
                ),
                modelLaunchDate: getDateFromString("2024-11-01"),
                modelGenerateBaseURL: "https://generativelanguage.googleapis.com/v1beta/models/gemini-3-pro-image-preview:generateContent",
                modelAPIDocumentationURL: "https://ai.google.dev/gemini-api/docs/image-generation",
                active: true
            ),
            ConnectionModel(
                connectionId: EnumConnectionCode.GOOGLE_CLOUD.connectionId,
                modelId: EnumConnectionModelCode.GOOGLE_GEMINI_PRO_IMAGE_EDIT.modelId,
                modelCode: EnumConnectionModelCode.GOOGLE_GEMINI_PRO_IMAGE_EDIT,
                modelSetType: EnumSetType.EDIT_PROMPT,
                modelName: "Nano Banana Pro (3 Pro)",
                modelDescription: "Gemini 3 Pro Image Preview - Advanced image editing. SD=2K, HD=4K resolution.",
                modelSupportedParams: ConnectionModelSupportParams(
                    prompt: true,
                    negativePrompt: false,
                    maxPromptLength: 4000,
                    dimensions: ["1024x1024", "832x1248", "1248x832", "864x1184", "1184x864", "896x1152", "1152x896", "768x1344", "1344x768", "1536x672"],
                    quality: true,
                    variant: false,
                    style: false,
                    count: 6,
                    autoEnhance: false,
                    responseModalities: [.TEXT, .IMAGE]
                ),
                modelLaunchDate: getDateFromString("2024-11-01"),
                modelGenerateBaseURL: "https://generativelanguage.googleapis.com/v1beta/models/gemini-3-pro-image-preview:generateContent",
                modelAPIDocumentationURL: "https://ai.google.dev/gemini-api/docs/image-generation",
                active: true
            ),
            ConnectionModel(
                connectionId: EnumConnectionCode.GOOGLE_CLOUD.connectionId,
                modelId: EnumConnectionModelCode.GOOGLE_IMAGEN_3.modelId,
                modelCode: EnumConnectionModelCode.GOOGLE_IMAGEN_3,
                modelSetType: EnumSetType.GENERATE,
                modelName: "Imagen 3",
                modelDescription: "Google's Imagen 3 - High-quality photorealistic image generation at 1K resolution.",
                modelSupportedParams: ConnectionModelSupportParams(
                    prompt: true,
                    negativePrompt: false,
                    maxPromptLength: 4000,
                    dimensions: ["1024x1024", "768x1024", "1024x768", "576x1024", "1024x576"],
                    quality: false,
                    variant: false,
                    style: false,
                    count: 6,
                    autoEnhance: false,
                    responseModalities: []
                ),
                modelLaunchDate: getDateFromString("2024-12-01"),
                modelGenerateBaseURL: "https://generativelanguage.googleapis.com/v1beta/models/imagen-3.0-generate-002:predict",
                modelAPIDocumentationURL: "https://ai.google.dev/gemini-api/docs/imagen",
                active: true
            ),
            ConnectionModel(
                connectionId: EnumConnectionCode.GOOGLE_CLOUD.connectionId,
                modelId: EnumConnectionModelCode.GOOGLE_IMAGEN_4_FAST.modelId,
                modelCode: EnumConnectionModelCode.GOOGLE_IMAGEN_4_FAST,
                modelSetType: EnumSetType.GENERATE,
                modelName: "Imagen 4 Fast",
                modelDescription: "Google's Imagen 4 Fast - Quick image generation at 1K resolution. $0.02/image.",
                modelSupportedParams: ConnectionModelSupportParams(
                    prompt: true,
                    negativePrompt: false,
                    maxPromptLength: 4000,
                    dimensions: ["1024x1024", "768x1024", "1024x768", "576x1024", "1024x576"],
                    quality: false,
                    variant: false,
                    style: false,
                    count: 6,
                    autoEnhance: false,
                    responseModalities: []
                ),
                modelLaunchDate: getDateFromString("2024-12-01"),
                modelGenerateBaseURL: "https://generativelanguage.googleapis.com/v1beta/models/imagen-4.0-fast-generate-001:predict",
                modelAPIDocumentationURL: "https://ai.google.dev/gemini-api/docs/imagen",
                active: true
            ),
            ConnectionModel(
                connectionId: EnumConnectionCode.GOOGLE_CLOUD.connectionId,
                modelId: EnumConnectionModelCode.GOOGLE_IMAGEN_4_STANDARD.modelId,
                modelCode: EnumConnectionModelCode.GOOGLE_IMAGEN_4_STANDARD,
                modelSetType: EnumSetType.GENERATE,
                modelName: "Imagen 4 Standard",
                modelDescription: "Google's Imagen 4 Standard - High-quality image generation. SD=1K, HD=2K resolution. $0.04/image.",
                modelSupportedParams: ConnectionModelSupportParams(
                    prompt: true,
                    negativePrompt: false,
                    maxPromptLength: 4000,
                    dimensions: ["1024x1024", "768x1024", "1024x768", "576x1024", "1024x576"],
                    quality: true,
                    variant: false,
                    style: false,
                    count: 6,
                    autoEnhance: false,
                    responseModalities: []
                ),
                modelLaunchDate: getDateFromString("2024-12-01"),
                modelGenerateBaseURL: "https://generativelanguage.googleapis.com/v1beta/models/imagen-4.0-generate-001:predict",
                modelAPIDocumentationURL: "https://ai.google.dev/gemini-api/docs/imagen",
                active: true
            ),
            ConnectionModel(
                connectionId: EnumConnectionCode.GOOGLE_CLOUD.connectionId,
                modelId: EnumConnectionModelCode.GOOGLE_IMAGEN_4_ULTRA.modelId,
                modelCode: EnumConnectionModelCode.GOOGLE_IMAGEN_4_ULTRA,
                modelSetType: EnumSetType.GENERATE,
                modelName: "Imagen 4 Ultra",
                modelDescription: "Google's Imagen 4 Ultra - Premium quality image generation. SD=1K, HD=2K resolution. $0.06/image.",
                modelSupportedParams: ConnectionModelSupportParams(
                    prompt: true,
                    negativePrompt: false,
                    maxPromptLength: 4000,
                    dimensions: ["1024x1024", "768x1024", "1024x768", "576x1024", "1024x576"],
                    quality: true,
                    variant: false,
                    style: false,
                    count: 6,
                    autoEnhance: false,
                    responseModalities: []
                ),
                modelLaunchDate: getDateFromString("2024-12-01"),
                modelGenerateBaseURL: "https://generativelanguage.googleapis.com/v1beta/models/imagen-4.0-ultra-generate-001:predict",
                modelAPIDocumentationURL: "https://ai.google.dev/gemini-api/docs/imagen",
                active: true
            ),
            ConnectionModel(
                connectionId: EnumConnectionCode.GOOGLE_CLOUD.connectionId,
                modelId: EnumConnectionModelCode.GOOGLE_VEO_31.modelId,
                modelCode: EnumConnectionModelCode.GOOGLE_VEO_31,
                modelSetType: EnumSetType.VIDEO_TEXT,
                modelName: "Veo 3.1",
                modelDescription: "Google's Veo 3.1 - State-of-the-art video generation with native audio. Supports text/image/video input. $0.40/sec.",
                modelSupportedParams: ConnectionModelSupportParams(
                    prompt: true,
                    negativePrompt: true,
                    maxPromptLength: 1024,
                    dimensions: ["1280x720", "720x1280", "1920x1080", "1080x1920"],
                    quality: true,
                    variant: false,
                    style: false,
                    count: 1,
                    autoEnhance: false,
                    responseModalities: [],
                    supportedDurations: [4, 6, 8],
                    supportsAudio: true,
                    supportsLastFrame: true,
                    supportsVideoInput: true
                ),
                modelLaunchDate: getDateFromString("2025-09-01"),
                modelGenerateBaseURL: "https://generativelanguage.googleapis.com/v1beta/models/veo-3.1-generate-preview:predictLongRunning",
                modelStatusBaseURL: "https://generativelanguage.googleapis.com/v1beta",
                modelAPIDocumentationURL: "https://ai.google.dev/gemini-api/docs/video",
                active: true
            ),
            ConnectionModel(
                connectionId: EnumConnectionCode.GOOGLE_CLOUD.connectionId,
                modelId: EnumConnectionModelCode.GOOGLE_VEO_31_FAST.modelId,
                modelCode: EnumConnectionModelCode.GOOGLE_VEO_31_FAST,
                modelSetType: EnumSetType.VIDEO_TEXT,
                modelName: "Veo 3.1 Fast",
                modelDescription: "Google's Veo 3.1 Fast - Quick video generation with audio, optimized for speed. $0.15/sec.",
                modelSupportedParams: ConnectionModelSupportParams(
                    prompt: true,
                    negativePrompt: true,
                    maxPromptLength: 1024,
                    dimensions: ["1280x720", "720x1280", "1920x1080", "1080x1920"],
                    quality: true,
                    variant: false,
                    style: false,
                    count: 1,
                    autoEnhance: false,
                    responseModalities: [],
                    supportedDurations: [4, 6, 8],
                    supportsAudio: true,
                    supportsLastFrame: true,
                    supportsVideoInput: true
                ),
                modelLaunchDate: getDateFromString("2025-09-01"),
                modelGenerateBaseURL: "https://generativelanguage.googleapis.com/v1beta/models/veo-3.1-fast-generate-preview:predictLongRunning",
                modelStatusBaseURL: "https://generativelanguage.googleapis.com/v1beta",
                modelAPIDocumentationURL: "https://ai.google.dev/gemini-api/docs/video",
                active: true
            ),
            ConnectionModel(
                connectionId: EnumConnectionCode.GOOGLE_CLOUD.connectionId,
                modelId: EnumConnectionModelCode.GOOGLE_VEO_3.modelId,
                modelCode: EnumConnectionModelCode.GOOGLE_VEO_3,
                modelSetType: EnumSetType.VIDEO_TEXT,
                modelName: "Veo 3",
                modelDescription: "Google's Veo 3 - High-quality video generation with native audio. 720p/1080p. $0.40/sec.",
                modelSupportedParams: ConnectionModelSupportParams(
                    prompt: true,
                    negativePrompt: true,
                    maxPromptLength: 1024,
                    dimensions: ["1280x720", "720x1280", "1920x1080", "1080x1920"],
                    quality: true,
                    variant: false,
                    style: false,
                    count: 1,
                    autoEnhance: false,
                    responseModalities: [],
                    supportedDurations: [4, 6, 8],
                    supportsAudio: true,
                    supportsLastFrame: true,
                    supportsVideoInput: false
                ),
                modelLaunchDate: getDateFromString("2025-07-01"),
                modelGenerateBaseURL: "https://generativelanguage.googleapis.com/v1beta/models/veo-3.0-generate-001:predictLongRunning",
                modelStatusBaseURL: "https://generativelanguage.googleapis.com/v1beta",
                modelAPIDocumentationURL: "https://ai.google.dev/gemini-api/docs/video",
                active: true
            ),
            ConnectionModel(
                connectionId: EnumConnectionCode.GOOGLE_CLOUD.connectionId,
                modelId: EnumConnectionModelCode.GOOGLE_VEO_3_FAST.modelId,
                modelCode: EnumConnectionModelCode.GOOGLE_VEO_3_FAST,
                modelSetType: EnumSetType.VIDEO_TEXT,
                modelName: "Veo 3 Fast",
                modelDescription: "Google's Veo 3 Fast - Quick video generation with audio. 720p/1080p. $0.15/sec.",
                modelSupportedParams: ConnectionModelSupportParams(
                    prompt: true,
                    negativePrompt: true,
                    maxPromptLength: 1024,
                    dimensions: ["1280x720", "720x1280", "1920x1080", "1080x1920"],
                    quality: true,
                    variant: false,
                    style: false,
                    count: 1,
                    autoEnhance: false,
                    responseModalities: [],
                    supportedDurations: [4, 6, 8],
                    supportsAudio: true,
                    supportsLastFrame: true,
                    supportsVideoInput: false
                ),
                modelLaunchDate: getDateFromString("2025-07-01"),
                modelGenerateBaseURL: "https://generativelanguage.googleapis.com/v1beta/models/veo-3.0-fast-generate-001:predictLongRunning",
                modelStatusBaseURL: "https://generativelanguage.googleapis.com/v1beta",
                modelAPIDocumentationURL: "https://ai.google.dev/gemini-api/docs/video",
                active: true
            ),
            ConnectionModel(
                connectionId: EnumConnectionCode.GOOGLE_CLOUD.connectionId,
                modelId: EnumConnectionModelCode.GOOGLE_VEO_2.modelId,
                modelCode: EnumConnectionModelCode.GOOGLE_VEO_2,
                modelSetType: EnumSetType.VIDEO_TEXT,
                modelName: "Veo 2",
                modelDescription: "Google's Veo 2 - Video generation at 720p. Silent output (no audio). $0.35/sec.",
                modelSupportedParams: ConnectionModelSupportParams(
                    prompt: true,
                    negativePrompt: true,
                    maxPromptLength: 1024,
                    dimensions: ["1280x720", "720x1280"],
                    quality: false,
                    variant: false,
                    style: false,
                    count: 1,
                    autoEnhance: false,
                    responseModalities: [],
                    supportedDurations: [5, 6, 8],
                    supportsAudio: false,
                    supportsLastFrame: true,
                    supportsVideoInput: false
                ),
                modelLaunchDate: getDateFromString("2025-04-01"),
                modelGenerateBaseURL: "https://generativelanguage.googleapis.com/v1beta/models/veo-2.0-generate-001:predictLongRunning",
                modelStatusBaseURL: "https://generativelanguage.googleapis.com/v1beta",
                modelAPIDocumentationURL: "https://ai.google.dev/gemini-api/docs/video",
                active: true
            )
        ]
    }
}

