import Foundation

struct StabilityModels {
    
    static func createModels() -> [ConnectionModel] {
        return [
            ConnectionModel(
                connectionId: EnumConnectionCode.STABILITY_AI.connectionId,
                modelId: EnumConnectionModelCode.STABILITY_ULTRA.modelId,
                modelCode: EnumConnectionModelCode.STABILITY_ULTRA,
                modelSetType: EnumSetType.GENERATE,
                modelName: "Stable Ultra",
                modelDescription: "Stable Image Ultra creates the highest quality images with unprecedented prompt understanding.",
                modelSupportedParams: ConnectionModelSupportParams(
                    prompt: true,
                    negativePrompt: true,
                    maxPromptLength: 1024,
                    dimensions: ["1024x1024", "576x1024", "1024x576", "1344x576", "576x1344", "1536x1024", "1024x1536", "1280x1024", "1024x1280"],
                    quality: false,
                    variant: true,
                    style: false,
                    count: 6,
                    autoEnhance: true
                ),
                modelLaunchDate: getDateFromString("2023-07-26"),
                modelGenerateBaseURL: "https://api.stability.ai/v2beta/stable-image/generate/ultra",
                modelAPIDocumentationURL: "https://platform.stability.ai/docs/api-reference#tag/Generate/paths/~1v2beta~1stable-image~1generate~1ultra/post",
                active: true
            ),
            ConnectionModel(
                connectionId: EnumConnectionCode.STABILITY_AI.connectionId,
                modelId: EnumConnectionModelCode.STABILITY_CORE.modelId,
                modelCode: EnumConnectionModelCode.STABILITY_CORE,
                modelSetType: EnumSetType.GENERATE,
                modelName: "Stable Core",
                modelDescription: "Stable Image Core represents the best quality achievable at high speed.",
                modelSupportedParams: ConnectionModelSupportParams(
                    prompt: true,
                    negativePrompt: true,
                    maxPromptLength: 1024,
                    dimensions: ["1024x1024", "576x1024", "1024x576", "1344x576", "576x1344", "1536x1024", "1024x1536", "1280x1024", "1024x1280"],
                    quality: false,
                    variant: true,
                    style: false,
                    count: 6,
                    autoEnhance: true
                ),
                modelLaunchDate: getDateFromString("2023-07-26"),
                modelGenerateBaseURL: "https://api.stability.ai/v2beta/stable-image/generate/core",
                modelAPIDocumentationURL: "https://platform.stability.ai/docs/api-reference#tag/Generate/paths/~1v2beta~1stable-image~1generate~1core/post",
                active: true
            ),
            ConnectionModel(
                connectionId: EnumConnectionCode.STABILITY_AI.connectionId,
                modelId: EnumConnectionModelCode.STABILITY_SDXL.modelId,
                modelCode: EnumConnectionModelCode.STABILITY_SDXL,
                modelSetType: EnumSetType.GENERATE,
                modelName: "Stable XL 1.0 (SDXL)",
                modelDescription: "Stable Diffusion XL (SDXL) is a powerful text-to-image generation model.",
                modelSupportedParams: ConnectionModelSupportParams(
                    prompt: true,
                    negativePrompt: true,
                    maxPromptLength: 1024,
                    dimensions: ["1024x1024", "1152x896", "896x1152", "1216x832", "1344x768", "768x1344", "1536x640", "640x1536"],
                    quality: false,
                    variant: true,
                    style: false,
                    count: 6,
                    autoEnhance: true
                ),
                modelLaunchDate: getDateFromString("2023-07-26"),
                modelGenerateBaseURL: "https://api.stability.ai/v1/generation/stable-diffusion-xl-1024-v1-0/text-to-image",
                modelAPIDocumentationURL: "https://platform.stability.ai/docs/api-reference#tag/SDXL-and-SD1.6",
                active: true
            ),
            ConnectionModel(
                connectionId: EnumConnectionCode.STABILITY_AI.connectionId,
                modelId: EnumConnectionModelCode.STABILITY_SD3.modelId,
                modelCode: EnumConnectionModelCode.STABILITY_SD3,
                modelSetType: EnumSetType.GENERATE,
                modelName: "Stable 3.0 Large",
                modelDescription: "Generate images using Stable Diffusion 3 Large (SD3). This model is deprecated - please use SD 3.5 models instead.",
                modelSupportedParams: ConnectionModelSupportParams(
                    prompt: true,
                    negativePrompt: true,
                    maxPromptLength: 1024,
                    dimensions: ["1024x1024", "576x1024", "1024x576", "1344x576", "576x1344", "1536x1024", "1024x1536", "1280x1024", "1024x1280"],
                    quality: false,
                    variant: true,
                    style: false,
                    count: 6,
                    autoEnhance: true
                ),
                modelLaunchDate: getDateFromString("2023-07-26"),
                modelDeprecationDate: getDateFromString("2024-10-01"),
                modelGenerateBaseURL: "https://api.stability.ai/v2beta/stable-image/generate/sd3",
                modelAPIDocumentationURL: "https://platform.stability.ai/docs/api-reference#tag/Generate/paths/~1v2beta~1stable-image~1generate~1sd3/post",
                active: false
            ),
            ConnectionModel(
                connectionId: EnumConnectionCode.STABILITY_AI.connectionId,
                modelId: EnumConnectionModelCode.STABILITY_SD3_TURBO.modelId,
                modelCode: EnumConnectionModelCode.STABILITY_SD3_TURBO,
                modelSetType: EnumSetType.GENERATE,
                modelName: "Stable 3.0 Turbo",
                modelDescription: "Generate images using Stable Diffusion 3 Large Turbo (SD3 Turbo). This model is deprecated - please use SD 3.5 Large Turbo instead.",
                modelSupportedParams: ConnectionModelSupportParams(
                    prompt: true,
                    negativePrompt: true,
                    maxPromptLength: 1024,
                    dimensions: ["1024x1024", "576x1024", "1024x576", "1344x576", "576x1344", "1536x1024", "1024x1536", "1280x1024", "1024x1280"],
                    quality: false,
                    variant: true,
                    style: false,
                    count: 6,
                    autoEnhance: true
                ),
                modelLaunchDate: getDateFromString("2023-07-26"),
                modelDeprecationDate: getDateFromString("2024-10-01"),
                modelGenerateBaseURL: "https://api.stability.ai/v2beta/stable-image/generate/sd3",
                modelAPIDocumentationURL: "https://platform.stability.ai/docs/api-reference#tag/Generate/paths/~1v2beta~1stable-image~1generate~1sd3/post",
                active: false
            ),
            ConnectionModel(
                connectionId: EnumConnectionCode.STABILITY_AI.connectionId,
                modelId: EnumConnectionModelCode.STABILITY_SD35_LARGE.modelId,
                modelCode: EnumConnectionModelCode.STABILITY_SD35_LARGE,
                modelSetType: EnumSetType.GENERATE,
                modelName: "Stable 3.5 Large",
                modelDescription: "Generate images using Stable Diffusion 3.5 Large (SD3.5), our most capable model for high-quality image generation.",
                modelSupportedParams: ConnectionModelSupportParams(
                    prompt: true,
                    negativePrompt: true,
                    maxPromptLength: 1024,
                    dimensions: ["1024x1024", "576x1024", "1024x576", "1344x576", "576x1344", "1536x1024", "1024x1536", "1280x1024", "1024x1280"],
                    quality: false,
                    variant: true,
                    style: false,
                    count: 6,
                    autoEnhance: true
                ),
                modelLaunchDate: getDateFromString("2024-10-01"),
                modelGenerateBaseURL: "https://api.stability.ai/v2beta/stable-image/generate/sd3",
                modelAPIDocumentationURL: "https://platform.stability.ai/docs/api-reference#tag/Generate/paths/~1v2beta~1stable-image~1generate~1sd3/post",
                active: true
            ),
            ConnectionModel(
                connectionId: EnumConnectionCode.STABILITY_AI.connectionId,
                modelId: EnumConnectionModelCode.STABILITY_SD35_LARGE_TURBO.modelId,
                modelCode: EnumConnectionModelCode.STABILITY_SD35_LARGE_TURBO,
                modelSetType: EnumSetType.GENERATE,
                modelName: "Stable 3.5 Large Turbo",
                modelDescription: "Generate images using Stable Diffusion 3.5 Large Turbo (SD3.5 Turbo), a faster version of our most capable model.",
                modelSupportedParams: ConnectionModelSupportParams(
                    prompt: true,
                    negativePrompt: true,
                    maxPromptLength: 1024,
                    dimensions: ["1024x1024", "576x1024", "1024x576", "1344x576", "576x1344", "1536x1024", "1024x1536", "1280x1024", "1024x1280"],
                    quality: false,
                    variant: true,
                    style: false,
                    count: 6,
                    autoEnhance: true
                ),
                modelLaunchDate: getDateFromString("2024-10-01"),
                modelGenerateBaseURL: "https://api.stability.ai/v2beta/stable-image/generate/sd3",
                modelAPIDocumentationURL: "https://platform.stability.ai/docs/api-reference#tag/Generate/paths/~1v2beta~1stable-image~1generate~1sd3/post",
                active: true
            ),
            ConnectionModel(
                connectionId: EnumConnectionCode.STABILITY_AI.connectionId,
                modelId: EnumConnectionModelCode.STABILITY_SD35_MEDIUM.modelId,
                modelCode: EnumConnectionModelCode.STABILITY_SD35_MEDIUM,
                modelSetType: EnumSetType.GENERATE,
                modelName: "Stable 3.5 Medium",
                modelDescription: "Generate images using Stable Diffusion 3.5 Medium (SD3.5), balancing quality and speed for efficient generation.",
                modelSupportedParams: ConnectionModelSupportParams(
                    prompt: true,
                    negativePrompt: true,
                    maxPromptLength: 1024,
                    dimensions: ["1024x1024", "576x1024", "1024x576", "1344x576", "576x1344", "1536x1024", "1024x1536", "1280x1024", "1024x1280"],
                    quality: false,
                    variant: true,
                    style: false,
                    count: 6,
                    autoEnhance: true
                ),
                modelLaunchDate: getDateFromString("2024-10-01"),
                modelGenerateBaseURL: "https://api.stability.ai/v2beta/stable-image/generate/sd3",
                modelAPIDocumentationURL: "https://platform.stability.ai/docs/api-reference#tag/Generate/paths/~1v2beta~1stable-image~1generate~1sd3/post",
                active: true
            ),
            ConnectionModel(
                connectionId: EnumConnectionCode.STABILITY_AI.connectionId,
                modelId: EnumConnectionModelCode.STABILITY_SD35_FLASH.modelId,
                modelCode: EnumConnectionModelCode.STABILITY_SD35_FLASH,
                modelSetType: EnumSetType.GENERATE,
                modelName: "Stable 3.5 Flash",
                modelDescription: "Generate images using Stable Diffusion 3.5 Flash (SD3.5), our fastest model for quick generations.",
                modelSupportedParams: ConnectionModelSupportParams(
                    prompt: true,
                    negativePrompt: true,
                    maxPromptLength: 1024,
                    dimensions: ["1024x1024", "576x1024", "1024x576", "1344x576", "576x1344", "1536x1024", "1024x1536", "1280x1024", "1024x1280"],
                    quality: false,
                    variant: true,
                    style: false,
                    count: 6,
                    autoEnhance: true
                ),
                modelLaunchDate: getDateFromString("2024-10-01"),
                modelGenerateBaseURL: "https://api.stability.ai/v2beta/stable-image/generate/sd3",
                modelAPIDocumentationURL: "https://platform.stability.ai/docs/api-reference#tag/Generate/paths/~1v2beta~1stable-image~1generate~1sd3/post",
                active: true
            ),
            ConnectionModel(
                connectionId: EnumConnectionCode.STABILITY_AI.connectionId,
                modelId: EnumConnectionModelCode.STABILITY_CREATIVE_UPSCALE.modelId,
                modelCode: EnumConnectionModelCode.STABILITY_CREATIVE_UPSCALE,
                modelSetType: EnumSetType.EDIT_UPSCALE,
                modelName: "Stable Creative Upscale",
                modelDescription: "Takes images between 64x64 and 1 megapixel and upscales them all the way to 4K resolution.",
                modelSupportedParams: ConnectionModelSupportParams(
                    prompt: true,
                    negativePrompt: true,
                    maxPromptLength: 1024,
                    dimensions: ["1024x1024", "576x1024", "1024x576", "768x1024", "1024x768"],
                    quality: false,
                    variant: false,
                    style: false,
                    count: 6,
                    autoEnhance: true
                ),
                modelLaunchDate: getDateFromString("2023-07-26"),
                modelGenerateBaseURL: "https://api.stability.ai/v2beta/stable-image/upscale/creative",
                modelAPIDocumentationURL: "https://platform.stability.ai/docs/api-reference#tag/Upscale/paths/~1v2beta~1stable-image~1upscale~1creative/post",
                active: true
            ),
            ConnectionModel(
                connectionId: EnumConnectionCode.STABILITY_AI.connectionId,
                modelId: EnumConnectionModelCode.STABILITY_CONSERVATIVE_UPSCALE.modelId,
                modelCode: EnumConnectionModelCode.STABILITY_CONSERVATIVE_UPSCALE,
                modelSetType: EnumSetType.EDIT_UPSCALE,
                modelName: "Stable Conservative Upscale",
                modelDescription: "Takes images between 64x64 and 1 megapixel and upscales them all the way to 4K resolution.",
                modelSupportedParams: ConnectionModelSupportParams(
                    prompt: true,
                    negativePrompt: true,
                    maxPromptLength: 1024,
                    dimensions: ["1024x1024", "576x1024", "1024x576", "768x1024", "1024x768"],
                    quality: false,
                    variant: false,
                    style: false,
                    count: 6,
                    autoEnhance: true
                ),
                modelLaunchDate: getDateFromString("2023-07-26"),
                modelGenerateBaseURL: "https://api.stability.ai/v2beta/stable-image/upscale/conservative",
                modelAPIDocumentationURL: "https://platform.stability.ai/docs/api-reference#tag/Upscale/paths/~1v2beta~1stable-image~1upscale~1conservative/post",
                active: true
            ),
            ConnectionModel(
                connectionId: EnumConnectionCode.STABILITY_AI.connectionId,
                modelId: EnumConnectionModelCode.STABILITY_ERASE.modelId,
                modelCode: EnumConnectionModelCode.STABILITY_ERASE,
                modelSetType: EnumSetType.EDIT_MASK_ERASE,
                modelName: "Stable Erase",
                modelDescription: "The Erase service removes unwanted objects, such as blemishes on portraits or items on desks, using image masks.",
                modelSupportedParams: ConnectionModelSupportParams(
                    prompt: true,
                    negativePrompt: true,
                    maxPromptLength: 1024,
                    dimensions: ["1024x1024", "576x1024", "1024x576", "768x1024", "1024x768"],
                    quality: false,
                    variant: false,
                    style: false,
                    count: 6,
                    autoEnhance: true
                ),
                modelLaunchDate: getDateFromString("2023-07-26"),
                modelGenerateBaseURL: "https://api.stability.ai/v2beta/stable-image/edit/erase",
                modelAPIDocumentationURL: "https://platform.stability.ai/docs/api-reference#tag/Edit/paths/~1v2beta~1stable-image~1edit~1erase/post",
                active: true
            ),
            ConnectionModel(
                connectionId: EnumConnectionCode.STABILITY_AI.connectionId,
                modelId: EnumConnectionModelCode.STABILITY_INPAINT.modelId,
                modelCode: EnumConnectionModelCode.STABILITY_INPAINT,
                modelSetType: EnumSetType.EDIT_MASK,
                modelName: "Stable Inpaint",
                modelDescription: "Intelligently modify images by filling in or replacing specified areas with new content based on the content of a mask image.",
                modelSupportedParams: ConnectionModelSupportParams(
                    prompt: true,
                    negativePrompt: true,
                    maxPromptLength: 1024,
                    dimensions: ["1024x1024", "576x1024", "1024x576", "768x1024", "1024x768"],
                    quality: false,
                    variant: false,
                    style: false,
                    count: 6,
                    autoEnhance: true
                ),
                modelLaunchDate: getDateFromString("2023-07-26"),
                modelGenerateBaseURL: "https://api.stability.ai/v2beta/stable-image/edit/inpaint",
                modelAPIDocumentationURL: "https://platform.stability.ai/docs/api-reference#tag/Edit/paths/~1v2beta~1stable-image~1edit~1inpaint/post",
                active: true
            ),
            ConnectionModel(
                connectionId: EnumConnectionCode.STABILITY_AI.connectionId,
                modelId: EnumConnectionModelCode.STABILITY_OUTPAINT.modelId,
                modelCode: EnumConnectionModelCode.STABILITY_OUTPAINT,
                modelSetType: EnumSetType.EDIT_EXPAND,
                modelName: "Stable Outpaint",
                modelDescription: "The Outpaint service inserts additional content in an image to fill in the space in any direction.",
                modelSupportedParams: ConnectionModelSupportParams(
                    prompt: true,
                    negativePrompt: true,
                    maxPromptLength: 1024,
                    dimensions: ["1024x1024", "576x1024", "1024x576", "768x1024", "1024x768"],
                    quality: false,
                    variant: false,
                    style: false,
                    count: 6,
                    autoEnhance: true
                ),
                modelLaunchDate: getDateFromString("2023-07-26"),
                modelGenerateBaseURL: "https://api.stability.ai/v2beta/stable-image/edit/outpaint",
                modelAPIDocumentationURL: "https://platform.stability.ai/docs/api-reference#tag/Edit/paths/~1v2beta~1stable-image~1edit~1outpaint/post",
                active: true
            ),
            ConnectionModel(
                connectionId: EnumConnectionCode.STABILITY_AI.connectionId,
                modelId: EnumConnectionModelCode.STABILITY_SEARCH_AND_REPLACE.modelId,
                modelCode: EnumConnectionModelCode.STABILITY_SEARCH_AND_REPLACE,
                modelSetType: EnumSetType.EDIT_REPLACE,
                modelName: "Stable Search and Replace",
                modelDescription: "The Search and Replace service is a specific version of inpainting that does not require a mask.",
                modelSupportedParams: ConnectionModelSupportParams(
                    prompt: true,
                    negativePrompt: true,
                    maxPromptLength: 1024,
                    dimensions: ["1024x1024", "576x1024", "1024x576", "768x1024", "1024x768"],
                    quality: false,
                    variant: false,
                    style: false,
                    count: 6,
                    autoEnhance: true
                ),
                modelLaunchDate: getDateFromString("2023-07-26"),
                modelGenerateBaseURL: "https://api.stability.ai/v2beta/stable-image/edit/search-and-replace",
                modelAPIDocumentationURL: "https://platform.stability.ai/docs/api-reference#tag/Edit/paths/~1v2beta~1stable-image~1edit~1search-and-replace/post",
                active: true
            ),
            ConnectionModel(
                connectionId: EnumConnectionCode.STABILITY_AI.connectionId,
                modelId: EnumConnectionModelCode.STABILITY_REMOVE_BACKGROUND.modelId,
                modelCode: EnumConnectionModelCode.STABILITY_REMOVE_BACKGROUND,
                modelSetType: EnumSetType.REMOVE_BACKGROUND,
                modelName: "Stable Remove Background",
                modelDescription: "The Remove Background service accurately segments the foreground from an image and implements and removes the background.",
                modelSupportedParams: ConnectionModelSupportParams(
                    prompt: true,
                    negativePrompt: true,
                    maxPromptLength: 1024,
                    dimensions: ["1024x1024", "576x1024", "1024x576", "768x1024", "1024x768"],
                    quality: false,
                    variant: false,
                    style: false,
                    count: 6,
                    autoEnhance: true
                ),
                modelLaunchDate: getDateFromString("2023-07-26"),
                modelGenerateBaseURL: "https://api.stability.ai/v2beta/stable-image/edit/remove-background",
                modelAPIDocumentationURL: "https://platform.stability.ai/docs/api-reference#tag/Edit/paths/~1v2beta~1stable-image~1edit~1remove-background/post",
                active: true
            ),
            ConnectionModel(
                connectionId: EnumConnectionCode.STABILITY_AI.connectionId,
                modelId: EnumConnectionModelCode.STABILITY_IMAGE_TO_VIDEO.modelId,
                modelCode: EnumConnectionModelCode.STABILITY_IMAGE_TO_VIDEO,
                modelSetType: EnumSetType.VIDEO_IMAGE,
                modelName: "Stable Image to Video",
                modelDescription: "Generate a short video based on an initial image with Stable Video Diffusion, a latent video diffusion model.",
                modelSupportedParams: ConnectionModelSupportParams(
                    prompt: true,
                    negativePrompt: true,
                    maxPromptLength: 1024,
                    dimensions: ["768x768", "576x1024", "1024x576"],
                    quality: false,
                    variant: false,
                    style: false,
                    count: 6,
                    autoEnhance: true
                ),
                modelLaunchDate: getDateFromString("2023-07-26"),
                modelGenerateBaseURL: "https://api.stability.ai/v2beta/image-to-video",
                modelAPIDocumentationURL: "https://platform.stability.ai/docs/api-reference#tag/Image-to-Video",
                active: false
            )
        ]
    }
}

