import Foundation

struct ReplicateModels {
    
    static func createModels() -> [ProviderModel] {
        return [
            ProviderModel(
                providerId: EnumProviderCode.REPLICATE.providerId,
                modelId: EnumProviderModelCode.REPLICATE_FLUX_SCHNELL.modelId,
                modelCode: EnumProviderModelCode.REPLICATE_FLUX_SCHNELL,
                modelSetType: EnumSetType.GENERATE,
                modelName: "FLUX.1 [schnell]",
                modelDescription: "The fastest image generation model tailored for local development and personal use.",
                modelSupportedParams: ProviderModelSupportParams(
                    prompt: true,
                    negativePrompt: true,
                    maxPromptLength: 256,
                    dimensions: ["1024x1024", "1920x1080", "2560x1080", "1024x1536", "1620x1080", "1280x1024", "1080x1920", "1080x2520"],
                    quality: false,
                    variant: true,
                    style: false,
                    count: 6,
                    autoEnhance: true
                ),
                modelLaunchDate: getDateFromString("2023-12-13"),
                modelGenerateBaseURL: "https://api.replicate.com/v1/models/black-forest-labs/flux-schnell/predictions",
                modelStatusBaseURL: "https://api.replicate.com/v1/predictions",
                modelAPIDocumentationURL: "https://replicate.com/black-forest-labs/flux-schnell?input=http",
                active: true
            ),
            ProviderModel(
                providerId: EnumProviderCode.REPLICATE.providerId,
                modelId: EnumProviderModelCode.REPLICATE_FLUX_DEV.modelId,
                modelCode: EnumProviderModelCode.REPLICATE_FLUX_DEV,
                modelSetType: EnumSetType.GENERATE,
                modelName: "FLUX.1 [dev]",
                modelDescription: "A 12 billion parameter rectified flow transformer capable of generating images from text descriptions.",
                modelSupportedParams: ProviderModelSupportParams(
                    prompt: true,
                    negativePrompt: true,
                    maxPromptLength: 256,
                    dimensions: ["1024x1024", "1920x1080", "2560x1080", "1024x1536", "1620x1080", "1280x1024", "1080x1920", "1080x2520"],
                    quality: false,
                    variant: true,
                    style: false,
                    count: 6,
                    autoEnhance: true
                ),
                modelLaunchDate: getDateFromString("2023-12-13"),
                modelGenerateBaseURL: "https://api.replicate.com/v1/models/black-forest-labs/flux-dev/predictions",
                modelStatusBaseURL: "https://api.replicate.com/v1/predictions",
                modelAPIDocumentationURL: "https://replicate.com/black-forest-labs/flux-dev?input=http",
                active: true
            ),
            ProviderModel(
                providerId: EnumProviderCode.REPLICATE.providerId,
                modelId: EnumProviderModelCode.REPLICATE_FLUX_PRO.modelId,
                modelCode: EnumProviderModelCode.REPLICATE_FLUX_PRO,
                modelSetType: EnumSetType.GENERATE,
                modelName: "FLUX.1 [pro]",
                modelDescription: "State-of-the-art image generation with top of the line prompt following, visual quality, image detail and output diversity.",
                modelSupportedParams: ProviderModelSupportParams(
                    prompt: true,
                    negativePrompt: true,
                    maxPromptLength: 256,
                    dimensions: ["1024x1024", "1920x1080", "1024x1536", "1620x1080", "1280x1024", "1080x1920"],
                    quality: false,
                    variant: true,
                    style: false,
                    count: 6,
                    autoEnhance: true
                ),
                modelLaunchDate: getDateFromString("2023-07-26"),
                modelGenerateBaseURL: "https://api.replicate.com/v1/models/black-forest-labs/flux-pro/predictions",
                modelStatusBaseURL: "https://api.replicate.com/v1/predictions",
                modelAPIDocumentationURL: "https://replicate.com/black-forest-labs/flux-pro?input=http",
                active: true
            ),
            ProviderModel(
                providerId: EnumProviderCode.REPLICATE.providerId,
                modelId: EnumProviderModelCode.REPLICATE_SEEDREAM_3.modelId,
                modelCode: EnumProviderModelCode.REPLICATE_SEEDREAM_3,
                modelSetType: EnumSetType.GENERATE,
                modelName: "Seedream 3",
                modelDescription: "A text-to-image model from ByteDance with support for native high-resolution (2K) image generation.",
                modelSupportedParams: ProviderModelSupportParams(
                    prompt: true,
                    negativePrompt: false,
                    maxPromptLength: 512,
                    dimensions: ["1024x1024", "1920x1080", "1080x1920", "1536x1024", "1024x1536", "1365x1024", "1024x1365", "2048x876"],
                    quality: false,
                    variant: true,
                    style: false,
                    count: 4,
                    autoEnhance: true
                ),
                modelLaunchDate: getDateFromString("2024-11-01"),
                modelGenerateBaseURL: "https://api.replicate.com/v1/models/bytedance/seedream-3/predictions",
                modelStatusBaseURL: "https://api.replicate.com/v1/predictions",
                modelAPIDocumentationURL: "https://replicate.com/bytedance/seedream-3",
                active: true
            ),
            ProviderModel(
                providerId: EnumProviderCode.REPLICATE.providerId,
                modelId: EnumProviderModelCode.REPLICATE_SEEDREAM_4.modelId,
                modelCode: EnumProviderModelCode.REPLICATE_SEEDREAM_4,
                modelSetType: EnumSetType.GENERATE,
                modelName: "Seedream 4",
                modelDescription: "Next-generation text-to-image model from ByteDance with native 4K resolution support and enhanced prompt understanding.",
                modelSupportedParams: ProviderModelSupportParams(
                    prompt: true,
                    negativePrompt: false,
                    maxPromptLength: 512,
                    dimensions: ["2048x2048", "2048x1536", "1536x2048", "2048x1152", "1152x2048", "2048x1365", "1365x2048", "2048x876"],
                    quality: false,
                    variant: true,
                    style: false,
                    count: 4,
                    autoEnhance: true
                ),
                modelLaunchDate: getDateFromString("2025-01-01"),
                modelGenerateBaseURL: "https://api.replicate.com/v1/models/bytedance/seedream-4/predictions",
                modelStatusBaseURL: "https://api.replicate.com/v1/predictions",
                modelAPIDocumentationURL: "https://replicate.com/bytedance/seedream-4",
                active: true
            ),
            ProviderModel(
                providerId: EnumProviderCode.REPLICATE.providerId,
                modelId: EnumProviderModelCode.REPLICATE_SEEDREAM_4_EDIT.modelId,
                modelCode: EnumProviderModelCode.REPLICATE_SEEDREAM_4_EDIT,
                modelSetType: EnumSetType.EDIT_PROMPT,
                modelName: "Seedream 4",
                modelDescription: "Edit images with text prompts using ByteDance's Seedream 4 model with multi-reference image support.",
                modelSupportedParams: ProviderModelSupportParams(
                    prompt: true,
                    negativePrompt: false,
                    maxPromptLength: 512,
                    dimensions: ["2048x2048", "2048x1536", "1536x2048", "2048x1152", "1152x2048", "2048x1365", "1365x2048", "2048x876"],
                    quality: false,
                    variant: true,
                    style: false,
                    count: 4,
                    autoEnhance: true
                ),
                modelLaunchDate: getDateFromString("2025-01-01"),
                modelGenerateBaseURL: "https://api.replicate.com/v1/models/bytedance/seedream-4/predictions",
                modelStatusBaseURL: "https://api.replicate.com/v1/predictions",
                modelAPIDocumentationURL: "https://replicate.com/bytedance/seedream-4",
                active: true
            ),
            ProviderModel(
                providerId: EnumProviderCode.REPLICATE.providerId,
                modelId: EnumProviderModelCode.REPLICATE_SEEDREAM_4_5.modelId,
                modelCode: EnumProviderModelCode.REPLICATE_SEEDREAM_4_5,
                modelSetType: EnumSetType.GENERATE,
                modelName: "Seedream 4.5",
                modelDescription: "Latest ByteDance text-to-image model with enhanced quality. Currently in beta with 2K resolution and 1:1 aspect ratio support.",
                modelSupportedParams: ProviderModelSupportParams(
                    prompt: true,
                    negativePrompt: false,
                    maxPromptLength: 512,
                    dimensions: ["2048x2048"],
                    quality: false,
                    variant: true,
                    style: false,
                    count: 4,
                    autoEnhance: true
                ),
                modelLaunchDate: getDateFromString("2025-06-01"),
                modelGenerateBaseURL: "https://api.replicate.com/v1/models/bytedance/seedream-4.5/predictions",
                modelStatusBaseURL: "https://api.replicate.com/v1/predictions",
                modelAPIDocumentationURL: "https://replicate.com/bytedance/seedream-4.5",
                active: true
            ),
            ProviderModel(
                providerId: EnumProviderCode.REPLICATE.providerId,
                modelId: EnumProviderModelCode.REPLICATE_SEEDREAM_4_5_EDIT.modelId,
                modelCode: EnumProviderModelCode.REPLICATE_SEEDREAM_4_5_EDIT,
                modelSetType: EnumSetType.EDIT_PROMPT,
                modelName: "Seedream 4.5",
                modelDescription: "Edit images with text prompts using ByteDance's latest Seedream 4.5 model. Currently in beta.",
                modelSupportedParams: ProviderModelSupportParams(
                    prompt: true,
                    negativePrompt: false,
                    maxPromptLength: 512,
                    dimensions: ["2048x2048"],
                    quality: false,
                    variant: true,
                    style: false,
                    count: 4,
                    autoEnhance: true
                ),
                modelLaunchDate: getDateFromString("2025-06-01"),
                modelGenerateBaseURL: "https://api.replicate.com/v1/models/bytedance/seedream-4.5/predictions",
                modelStatusBaseURL: "https://api.replicate.com/v1/predictions",
                modelAPIDocumentationURL: "https://replicate.com/bytedance/seedream-4.5",
                active: true
            ),
            ProviderModel(
                providerId: EnumProviderCode.REPLICATE.providerId,
                modelId: EnumProviderModelCode.REPLICATE_DREAMINA_3_1.modelId,
                modelCode: EnumProviderModelCode.REPLICATE_DREAMINA_3_1,
                modelSetType: EnumSetType.GENERATE,
                modelName: "Dreamina 3.1",
                modelDescription: "4MP text-to-image with enhanced cinematic quality, precise style control, improved text rendering, and commercial design optimization.",
                modelSupportedParams: ProviderModelSupportParams(
                    prompt: true,
                    negativePrompt: false,
                    maxPromptLength: 512,
                    dimensions: ["2048x2048", "2048x1536", "1536x2048", "2048x1365", "1365x2048", "2048x1152", "1152x2048", "2048x876", "876x2048"],
                    quality: false,
                    variant: true,
                    style: false,
                    count: 4,
                    autoEnhance: true
                ),
                modelLaunchDate: getDateFromString("2025-06-01"),
                modelGenerateBaseURL: "https://api.replicate.com/v1/models/bytedance/dreamina-3.1/predictions",
                modelStatusBaseURL: "https://api.replicate.com/v1/predictions",
                modelAPIDocumentationURL: "https://replicate.com/bytedance/dreamina-3.1",
                active: true
            ),
            ProviderModel(
                providerId: EnumProviderCode.REPLICATE.providerId,
                modelId: EnumProviderModelCode.REPLICATE_SEEDANCE_1_PRO.modelId,
                modelCode: EnumProviderModelCode.REPLICATE_SEEDANCE_1_PRO,
                modelSetType: EnumSetType.VIDEO_TEXT,
                modelName: "Seedance 1 Pro",
                modelDescription: "Text-to-video generation from ByteDance at up to 1080p resolution.",
                modelSupportedParams: ProviderModelSupportParams(
                    prompt: true,
                    negativePrompt: false,
                    maxPromptLength: 512,
                    dimensions: ["16:9", "4:3", "1:1", "3:4", "9:16", "21:9", "9:21"],
                    quality: false,
                    variant: false,
                    style: false,
                    count: 1,
                    autoEnhance: false,
                    supportedDurations: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                    supportedResolutions: ["480p", "720p", "1080p"],
                    supportedFPS: [24],
                    cameraFixed: true
                ),
                modelLaunchDate: getDateFromString("2025-01-01"),
                modelGenerateBaseURL: "https://api.replicate.com/v1/models/bytedance/seedance-1-pro/predictions",
                modelStatusBaseURL: "https://api.replicate.com/v1/predictions",
                modelAPIDocumentationURL: "https://replicate.com/bytedance/seedance-1-pro",
                active: true
            ),
            ProviderModel(
                providerId: EnumProviderCode.REPLICATE.providerId,
                modelId: EnumProviderModelCode.REPLICATE_SEEDANCE_1_PRO_EDIT.modelId,
                modelCode: EnumProviderModelCode.REPLICATE_SEEDANCE_1_PRO_EDIT,
                modelSetType: EnumSetType.VIDEO_IMAGE,
                modelName: "Seedance 1 Pro",
                modelDescription: "Image-to-video generation from ByteDance at up to 1080p resolution.",
                modelSupportedParams: ProviderModelSupportParams(
                    prompt: true,
                    negativePrompt: false,
                    maxPromptLength: 512,
                    dimensions: ["16:9", "4:3", "1:1", "3:4", "9:16", "21:9", "9:21"],
                    quality: false,
                    variant: false,
                    style: false,
                    count: 1,
                    autoEnhance: false,
                    supportedDurations: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                    supportedResolutions: ["480p", "720p", "1080p"],
                    supportedFPS: [24],
                    supportsLastFrame: true,
                    cameraFixed: true
                ),
                modelLaunchDate: getDateFromString("2025-01-01"),
                modelGenerateBaseURL: "https://api.replicate.com/v1/models/bytedance/seedance-1-pro/predictions",
                modelStatusBaseURL: "https://api.replicate.com/v1/predictions",
                modelAPIDocumentationURL: "https://replicate.com/bytedance/seedance-1-pro",
                active: true
            ),
            ProviderModel(
                providerId: EnumProviderCode.REPLICATE.providerId,
                modelId: EnumProviderModelCode.REPLICATE_SEEDANCE_1_PRO_FAST.modelId,
                modelCode: EnumProviderModelCode.REPLICATE_SEEDANCE_1_PRO_FAST,
                modelSetType: EnumSetType.VIDEO_TEXT,
                modelName: "Seedance 1 Pro Fast",
                modelDescription: "30-60% faster text-to-video generation from ByteDance with ~60% reduced cost.",
                modelSupportedParams: ProviderModelSupportParams(
                    prompt: true,
                    negativePrompt: false,
                    maxPromptLength: 512,
                    dimensions: ["16:9", "4:3", "1:1", "3:4", "9:16", "21:9", "9:21"],
                    quality: false,
                    variant: false,
                    style: false,
                    count: 1,
                    autoEnhance: false,
                    supportedDurations: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                    supportedResolutions: ["480p", "720p", "1080p"],
                    supportedFPS: [24],
                    cameraFixed: true
                ),
                modelLaunchDate: getDateFromString("2025-01-01"),
                modelGenerateBaseURL: "https://api.replicate.com/v1/models/bytedance/seedance-1-pro-fast/predictions",
                modelStatusBaseURL: "https://api.replicate.com/v1/predictions",
                modelAPIDocumentationURL: "https://replicate.com/bytedance/seedance-1-pro-fast",
                active: true
            ),
            ProviderModel(
                providerId: EnumProviderCode.REPLICATE.providerId,
                modelId: EnumProviderModelCode.REPLICATE_SEEDANCE_1_PRO_FAST_EDIT.modelId,
                modelCode: EnumProviderModelCode.REPLICATE_SEEDANCE_1_PRO_FAST_EDIT,
                modelSetType: EnumSetType.VIDEO_IMAGE,
                modelName: "Seedance 1 Pro Fast",
                modelDescription: "30-60% faster image-to-video generation from ByteDance with ~60% reduced cost.",
                modelSupportedParams: ProviderModelSupportParams(
                    prompt: true,
                    negativePrompt: false,
                    maxPromptLength: 512,
                    dimensions: ["16:9", "4:3", "1:1", "3:4", "9:16", "21:9", "9:21"],
                    quality: false,
                    variant: false,
                    style: false,
                    count: 1,
                    autoEnhance: false,
                    supportedDurations: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                    supportedResolutions: ["480p", "720p", "1080p"],
                    supportedFPS: [24],
                    supportsLastFrame: true,
                    cameraFixed: true
                ),
                modelLaunchDate: getDateFromString("2025-01-01"),
                modelGenerateBaseURL: "https://api.replicate.com/v1/models/bytedance/seedance-1-pro-fast/predictions",
                modelStatusBaseURL: "https://api.replicate.com/v1/predictions",
                modelAPIDocumentationURL: "https://replicate.com/bytedance/seedance-1-pro-fast",
                active: true
            ),
            ProviderModel(
                providerId: EnumProviderCode.REPLICATE.providerId,
                modelId: EnumProviderModelCode.REPLICATE_SEEDANCE_1_LITE.modelId,
                modelCode: EnumProviderModelCode.REPLICATE_SEEDANCE_1_LITE,
                modelSetType: EnumSetType.VIDEO_TEXT,
                modelName: "Seedance 1 Lite",
                modelDescription: "Lightweight text-to-video generation from ByteDance at up to 1080p resolution.",
                modelSupportedParams: ProviderModelSupportParams(
                    prompt: true,
                    negativePrompt: false,
                    maxPromptLength: 512,
                    dimensions: ["16:9", "4:3", "1:1", "3:4", "9:16", "21:9", "9:21"],
                    quality: false,
                    variant: false,
                    style: false,
                    count: 1,
                    autoEnhance: false,
                    supportedDurations: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                    supportedResolutions: ["480p", "720p", "1080p"],
                    supportedFPS: [24],
                    cameraFixed: true
                ),
                modelLaunchDate: getDateFromString("2025-01-01"),
                modelGenerateBaseURL: "https://api.replicate.com/v1/models/bytedance/seedance-1-lite/predictions",
                modelStatusBaseURL: "https://api.replicate.com/v1/predictions",
                modelAPIDocumentationURL: "https://replicate.com/bytedance/seedance-1-lite",
                active: true
            ),
            ProviderModel(
                providerId: EnumProviderCode.REPLICATE.providerId,
                modelId: EnumProviderModelCode.REPLICATE_SEEDANCE_1_LITE_EDIT.modelId,
                modelCode: EnumProviderModelCode.REPLICATE_SEEDANCE_1_LITE_EDIT,
                modelSetType: EnumSetType.VIDEO_IMAGE,
                modelName: "Seedance 1 Lite",
                modelDescription: "Lightweight image-to-video generation from ByteDance at up to 1080p resolution.",
                modelSupportedParams: ProviderModelSupportParams(
                    prompt: true,
                    negativePrompt: false,
                    maxPromptLength: 512,
                    dimensions: ["16:9", "4:3", "1:1", "3:4", "9:16", "21:9", "9:21"],
                    quality: false,
                    variant: false,
                    style: false,
                    count: 1,
                    autoEnhance: false,
                    supportedDurations: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                    supportedResolutions: ["480p", "720p", "1080p"],
                    supportedFPS: [24],
                    supportsLastFrame: true,
                    cameraFixed: true
                ),
                modelLaunchDate: getDateFromString("2025-01-01"),
                modelGenerateBaseURL: "https://api.replicate.com/v1/models/bytedance/seedance-1-lite/predictions",
                modelStatusBaseURL: "https://api.replicate.com/v1/predictions",
                modelAPIDocumentationURL: "https://replicate.com/bytedance/seedance-1-lite",
                active: true
            )
        ]
    }
}

